"Filed out from Dolphin Smalltalk 7"!

Smalltalk at: #InputConstants put: (PoolConstantsDictionary named: #InputConstants)!
InputConstants at: 'INPUT_HARDWARE' put: 16r2!
InputConstants at: 'INPUT_KEYBOARD' put: 16r1!
InputConstants at: 'INPUT_MOUSE' put: 16r0!
InputConstants at: 'KEYEVENTF_EXTENDEDKEY' put: 16r1!
InputConstants at: 'KEYEVENTF_KEYUP' put: 16r2!
InputConstants at: 'KEYEVENTF_SCANCODE' put: 16r8!
InputConstants at: 'KEYEVENTF_UNICODE' put: 16r4!
InputConstants at: 'MOUSEEVENTF_ABSOLUTE' put: 16r8000!
InputConstants at: 'MOUSEEVENTF_HWHEEL' put: 16r1000!
InputConstants at: 'MOUSEEVENTF_LEFTDOWN' put: 16r2!
InputConstants at: 'MOUSEEVENTF_LEFTUP' put: 16r4!
InputConstants at: 'MOUSEEVENTF_MIDDLEDOWN' put: 16r20!
InputConstants at: 'MOUSEEVENTF_MIDDLEUP' put: 16r40!
InputConstants at: 'MOUSEEVENTF_MOVE' put: 16r1!
InputConstants at: 'MOUSEEVENTF_MOVE_NOCOALESCE' put: 16r2000!
InputConstants at: 'MOUSEEVENTF_RIGHTDOWN' put: 16r8!
InputConstants at: 'MOUSEEVENTF_RIGHTUP' put: 16r10!
InputConstants at: 'MOUSEEVENTF_VIRTUALDESK' put: 16r4000!
InputConstants at: 'MOUSEEVENTF_WHEEL' put: 16r800!
InputConstants at: 'MOUSEEVENTF_XDOWN' put: 16r80!
InputConstants at: 'MOUSEEVENTF_XUP' put: 16r100!
InputConstants at: 'XBUTTON1' put: 16r1!
InputConstants at: 'XBUTTON2' put: 16r2!
InputConstants shrink!
